
/* tslint:disable */

/**
 * This file was automatically generated by Aven CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Aven Cloud schema and re-run 'aven pull'
 */

import { createClient, SiteLoad } from "@aven/client";

export type PricingPlans = {
  key?: string;
  title?: string;
  "price-per-month"?: number;
}[];

export type Zoom = boolean[];


export type SiteSchema = {
  "pricing-plans": PricingPlans;
  "zoom": Zoom;
}

const Cloud = createClient<SiteSchema>({
  siteName: "rocketship",
});
export default Cloud;


export type CloudLoad = SiteLoad<SiteSchema>;

