import React from "react";
import styled from "@emotion/styled";
import Title from "../components/Title";
import Main from "../components/Main";
import VideoSection from "../components/VideoSection";

export default function Home() {
  return (
    <>
      <VideoSection vimeoId="447066041" />
      <Main>
        <p>
          Aven is an *open* platform for *educators and creators* to
          independently *publish* their work, *monetize*, and connect to their
          *community*.
        </p>
      </Main>
      <Main>
        <p>
          Aven is generated by Eric Vicenti, an entrepreneur and software
          engineer from California.
        </p>
      </Main>
    </>
  );
}

// what is aven? mission?

// live episodes

// about evv

//

//

//

Home.meta = { title: "Aven" };
