import React from "react";
import styled from "@emotion/styled";
import Title from "../components/Title";
import Main from "../components/Main";
import VideoSection from "../components/VideoSection";

export default function Home() {
  return (
    <>
      <VideoSection vimeoId="447066041" />
      <Main>
        <Title>Aven Teaser</Title>
      </Main>
    </>
  );
}

// what is aven? mission?

// live episodes

// about evv

// Aven is an *open* platform for *educators and creators* to independently *publish* their work, *monetize*, and connect to their *community*.

//

// aven is generated by Eric Vicenti, an entereprenuer and software engineer from California.

Home.meta = { title: "Aven" };
