import React from 'react';
import styled from '@emotion/styled'

const H1 = styled.h1({
  color: 'green'
});

const Main = styled.main({
  maxWidth: 1200,
  borderLeftWidth: 1,
  borderRightWidth: 1,
  borderColor: 'green',
  backgroundColor: 'blue'
})

export default function Home() {
  return (
    <div>
      <Main>
        <H1>Aven2: Hopefully live reload with css</H1>
      </Main>
    </div>
  );
}


// what is aven? mission?

// live episodes

// about evv



// Aven is an *open* platform for *educators and creators* to independently *publish* their work, *monetize*, and connect to their *community*.

// 

// aven is generated by Eric Vicenti, an entereprenuer and software engineer from California.


Home.meta = { title: "Aven" };
