const fetch = require('node-fetch');
const argv = require('minimist')(process.argv.slice(2));
const { compile } = require('json-schema-to-typescript');
const { writeFile } = require('fs-extra');

async function pull(siteName, apiKey) {
  const res = await fetch('http://localhost:3001/api/site-schema', {
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: 'aven' }),
  });
  const resp = await res.json();
  const { siteSchema } = resp;
  const allRecords = {};
  for (let nodeKey in siteSchema) {
    const node = siteSchema[nodeKey];
    if (node.type === 'record') {
      allRecords[nodeKey] = node;
    }
  }
  const exportedInterfaces = [];
  const definedTypes = {};
  for (let recordKey in allRecords) {
    const record = allRecords[recordKey];
    const typeDef = await compile(record.record, recordKey, {
      bannerComment: '',
    });
    const typeKeyMatch = typeDef.match(/^export type (.*) =/);
    const typeKey = typeKeyMatch && typeKeyMatch[1];
    if (!typeKey) {
      throw new Error('Failed ts compilation');
    }
    definedTypes[recordKey] = typeKey;

    exportedInterfaces.push(typeDef);
  }
  exportedInterfaces.push(`
export type SiteSchema = {
${Object.entries(definedTypes)
  .map(([recordKey, typeKey]) => `  "${recordKey}": ${typeKey};`)
  .join('\n')}
}`);
  const genFile = `
/* tslint:disable */

/**
 * This file was automatically generated by Aven CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Aven Cloud schema and re-run 'aven pull'
 */

${exportedInterfaces.join('\n')}
`;
  const genFileLocation = `AvenCloud-${siteName}-Generated.ts`;
  await writeFile(genFileLocation, genFile);
  return { genFile, genFileLocation, exportedInterfaces, definedTypes };
}

function handleCli(argv) {
  if (argv.h === true) {
    console.log(`
Aven CLI tool

Usage:
aven pull SITE_NAME

        `);
  }

  const action = argv._[0];
  if (action === 'pull') {
    pull(argv._[1])
      .then(({ definedTypes, genFileLocation }) => {
        console.log(`Pulled ${Object.entries(definedTypes).length} properties to ${genFileLocation}`);
      })
      .catch((e) => {
        console.error('eerrorr', e);
      });
    return;
  }
  console.log('Command not found. Try -h');
  return;
}

handleCli(argv);
