/* eslint:disable */

/**
 * This file was automatically generated by Aven CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Aven Cloud schema and re-run 'aven pull'
 */

export type PricingPlans = {
  ok?: string;
  key?: string;
  title?: string;
  'price-per-month'?: number;
}[];

export type StatusHeader = string;

export type Title = string;

export type SiteSchema = {
  'pricing-plans': PricingPlans;
  'status-header': StatusHeader;
  title: Title;
};
